### ISSUE TITLE
Migrate to Selenium Webdriver

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#141]
@alvestrand @juberti @fippo @jan-ivar PTAL

About 25% in the Webdriver test refactoring it suddenly hit me ;) that I should probably share my plan to get some input and also to make sure no-one else is doing the same thing as it's quite a lot of work.

The grand plan:
## Part 1 (will be done now)
- [x] Refactor tests to use Selenium webdriver JS format, like in the [samples repo](https://github.com/webrtc/samples/tree/gh-pages/test)
- [x] Create a new repo under WebRTC for shared selenium parts (e.g. selenium-libs etc) and export to NPM. Then add it is a dependency for all WebRTC projects using it (testrtc, samples etc). I will also add the NPM chromedriver and webdriver NPM packages as a dependency in that repo to ensure it's all handled in one place.
### Question

I got a question regarding the tests, currently they are all in one [file](https://github.com/webrtc/adapter/blob/master/test/test.js) which is pretty big, WDYT about splitting it up? E.g. getUserMedia, PeerConnection and deviceEnumeration or some other type of grouping?
## Part 2 (Will be done later)
- [ ] Add CI support for Windows, most likely appveyor.com (already got it [running](https://ci.appveyor.com/project/KaptenJansson/adapter) with two tests), however it's not urgent as it does not support windows 10 thus no Edge support yet but it's coming as part of the BYO OS image feature. Also webdriver for edge is not finished yet however it can still be used as part of the windows insider releases.
- [ ] End goal is to have all the tests running on Mac OS, Linux (Debian based to start with) and Windows.

**Comment by KaptenJansson** [comment]
Part 1 is landed in #144 with the exception of pulling out webdriver to components to a separate repo.

**Comment by KaptenJansson** [comment]
Closing this as webdriver has landed as well as a new utilities repo has been created for shared selenium and test framework stuff. MS edge test stuff will have to be done later in a separate issue.
